import Head from 'next/head'
import {BiUserPlus} from 'react-icons/bi'
import Form from '../components/Form'
import Table from '../components/Table'
import {useState} from 'react'


export default function Home() {
  const [visible, setVisible] = useState(false)

  return (
    <section>
      <Head>
        <title>CRUD Application</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="py-5">
        <h1 className = "text-xl md:text-5xl text-center font-body py-10">Employeee Management</h1>
        <div className="container mx-auto flex justify-between py-5 border-b">
          <div className="left flex gap-3">
            <button onClick={() => setVisible(!visible)} className="flex bg-indigo-500 text-white px-4 py-2 border rounded-md hover:bg-gray-50 hover:border-indigo-500 hover:text-gray-800">Add Employeee<span className="px-1"><BiUserPlus size = {23}/></span></button>
          </div>

        </div>
          {visible ? <Form/> : null}
        <div className="container mx-auto">
          <Table/>
        </div>
      </main>
    </section>
  )
}
